# Xulebra

A two-player networked snake game, originally written for AIX 4.3 and
ported to modern POSIX systems.

## Requirements

- GCC or any C99-compliant compiler
- ncurses development headers (`libncurses-dev` on Debian/Ubuntu,
  `ncurses-devel` on Fedora/RHEL)

## Build

```
make
```

The binary is placed at `bin/xulebra`.  Object files go to `obj/`.

```
make clean    # remove generated files
```

## Usage

```
xulebra <mode> [options]
```

### Modes

| Flag | Description |
|------|-------------|
| `-1` | Single-player |
| `-s` | Server mode — also spawns a local client child process |
| `-c` | Client mode — connect to a running server |
| `-h` | Print help |

### Single-player options  (`-1`)

| Flag | Default | Description |
|------|---------|-------------|
| `-W <cols>` | 30 | Board width in cells (min 10) |
| `-H <rows>` | 20 | Board height in cells (min 5) |
| `-S <level>` | 5 | Speed level 1–10 (1 = slow, 10 = fast) |
| `-L <len>` | 3 | Initial snake length (max 20) |
| `-A <n>` | 1 | Apples on board at once (max 9) |
| `-N <n>` | 0 | Auto speed-up every N apples (0 = off) |
| `-T` | off | Wrap-around mode: exit wall re-enters opposite side |
| `-b` | off | Enable AI bot opponent (blue snake) |

In-game keys: `SPACE` pause · `Q` / `ESC` quit

### Network options  (`-s` / `-c`)

| Flag | Default | Description |
|------|---------|-------------|
| `-p <port>` | 2580 | TCP port (must be > 1024) |
| `-W <cols>` | 30 | Board width in cells (min 10) |
| `-H <rows>` | 20 | Board height in cells (min 5) |
| `-S <level>` | 5 | Speed level 1–10 |
| `-A <n>` | 1 | Apples on board (max 9) — server only |
| `-v` | off | Enable spectator slot — server only |
| `-h <host>` | localhost | Server hostname — client only |

### Examples

```bash
# Single-player, bigger board, faster start, bot opponent
xulebra -1 -W 40 -H 28 -S 7 -b

# Single-player with wrap-around and 3 apples
xulebra -1 -T -A 3

# Start a server on port 3000 with 2 apples and a spectator slot
xulebra -s -p 3000 -A 2 -v

# Connect as client to a remote server
xulebra -c -h 192.168.1.10 -p 3000
```

## Project layout

```
xulebra/
├── Makefile
├── README
├── include/          public headers
│   ├── defines.h     game constants and key bindings
│   ├── xulnet.h      network protocol constants and message types
│   ├── snake.h       Snake ADT types and function declarations
│   ├── colors.h      ncurses color pair IDs
│   ├── socket.h      TCP socket helper declarations
│   ├── score.h       hall-of-fame API
│   ├── server.h      server_run() declaration
│   ├── client.h      client_run() declaration
│   └── one_player.h  one_player() declaration
├── src/              implementation files
│   ├── main.c        entry point and mode dispatch
│   ├── snake.c       Snake ADT implementation
│   ├── colors.c      ncurses color initialisation
│   ├── socket.c      TCP connect / accept helpers
│   ├── score.c       hall-of-fame read/write/display
│   ├── server.c      network game server
│   ├── client.c      network game client
│   └── one_player.c  single-player game (includes AI bot)
├── obj/              object files (generated by make)
└── bin/              compiled binary (generated by make)
    └── xulebra
```

## Apple types

| Symbol | Colour | Effect |
|--------|--------|--------|
| `@` | Red | Normal — score + grow |
| `+` | Yellow | Speed-up — score + grow + faster |
| `o` | Cyan | Slow-down — score + grow + slower |

## Score database

Scores are stored in `/tmp/.xulebra.hof` (binary, capped at 100 records).
The hall-of-fame is displayed in-game after every session.
